version: '2'  
services:  
  php-fpm:
    build: ./docker/php/
    environment:
      TIMEZONE: Europe/Paris
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./app:/var/www/app
      - ./docker/logs/symfony:/var/www/symfony/app/logs
    working_dir: /var/www/app
    depends_on:
      - db
    volumes_from:
      - data
    tty: true
    networks:
        mynet:
            ipv4_address: 172.10.1.2

  nginx:
    image: nginx
    depends_on:
      - php-fpm
    volumes_from:
      - data
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/logs/nginx:/var/log/nginx
    ports:
      - 80:80
      - 8081:8081
    networks:
        mynet:
            ipv4_address: 172.10.1.3

  composer:
    image: composer:1.4
    volumes_from:
      - php-fpm
    working_dir: /var/www/app

  db:
    image: mariadb:10.1
    ports:
        - 3306:3306
    environment:
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: root
    volumes_from:
        - data
    networks:
        mynet:
            ipv4_address: 172.10.1.4

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dockersf_phpmyadmin
    links:
        - db
    ports:
        - 8080:80
    networks:
        mynet:
            ipv4_address: 172.10.1.5

  data:
    image: debian
    working_dir: /
    volumes:
        - /var/lib/postgresql
        - /var/log/nginx
        - /data
    tty: true

networks:
    mynet:
        driver: bridge
        ipam:
            config:
                - subnet: 172.10.0.0/16
                  gateway: 172.10.5.254